runtime: python38

instance_class: F1

handlers:
- url: /.*
  script: auto

libraries:
- name: numpy
  version: "1.21.0"
- name: pandas
  version: "1.5.0"

env_variables:
  BUCKET_NAME: "your-gcs-bucket"
