runtime: python39
instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"
  XTB_USER_ID: "17373384"
  XTB_PASSWORD: "Java090214&Clement06032005*"

entrypoint: gunicorn -b :$PORT start:app --timeout 120

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always

service_account: fit-guide-448220-b5@appspot.gserviceaccount.com
