runtime: python39
instance_class: F1

env_variables:
  PYTHONUNBUFFERED: "1"

entrypoint: gunicorn -b :$PORT start:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
  
handlers:
- url: /.*
  script: auto
  secure: always
