steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/trading-bot', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/trading-bot']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'trading-bot'
  - '--image'
  - 'gcr.io/$PROJECT_ID/trading-bot'
  - '--platform'
  - 'managed'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'XTB_USER_ID=${_XTB_USER_ID},XTB_PASSWORD=${_XTB_PASSWORD}'