
credentials:
    userId: "17373384"  # Remplacez par votre ID XTB
    password: "Java090214&Clement06032005*"  # Remplacez par votre mot de passe XTB

trading:
    symbol: "BITCOIN"
    timeframe: "1h"
    volume: 0.01
    max_positions: 3
    risk_per_trade: 0.02
    min_rr_ratio: 1.5
    max_spread_pips: 3.0
    
