steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/trading-bot', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/trading-bot']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'trading-bot'
  - '--image'
  - 'gcr.io/$PROJECT_ID/trading-bot'
  - '--platform'
  - 'managed'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'UTILISATEUR_XTB=${_UTILISATEUR_XTB},XTB_MOT_DE_PASSE=${_XTB_MOT_DE_PASSE}'

images:
- 'gcr.io/$PROJECT_ID/trading-bot'
